POST http://localhost:3000/api/questions
Content-Type: application/json

{
    "question": "Quelle est la capitale de la France ?",
    "answer": "Paris",
    "difficulty": "easy",
    "category": "Geographie",
    "type": "multiple",
    "options": [
        "Paris",
        "Londres",
        "Berlin",
        "Madrid"
    ]
}

######################################

PATCH http://localhost:3000/api/questions/68124dc28a5d5b2f3a41d826
Content-Type: application/json

{
    "question": "Quelle est la capitale de la France ?",
    "category": "Geographie",
    "type": "multiple"
}

######################################

GET http://localhost:3000/api/questions

#######################################

GET http://localhost:3000/api/questions/68124dc28a5d5b2f3a41d826

########################################

DELETE http://localhost:3000/api/questions/68124dc28a5d5b2f3a41d826